#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeWebApp.db
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HomeWebAppDB")]
	public partial class DBModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertvisitor(visitor instance);
    partial void Updatevisitor(visitor instance);
    partial void Deletevisitor(visitor instance);
    partial void InsertvisitorCustomMessageHistory(visitorCustomMessageHistory instance);
    partial void UpdatevisitorCustomMessageHistory(visitorCustomMessageHistory instance);
    partial void DeletevisitorCustomMessageHistory(visitorCustomMessageHistory instance);
    partial void InsertusersToVisitor(usersToVisitor instance);
    partial void UpdateusersToVisitor(usersToVisitor instance);
    partial void DeleteusersToVisitor(usersToVisitor instance);
    partial void InsertNFL_userPick(NFL_userPick instance);
    partial void UpdateNFL_userPick(NFL_userPick instance);
    partial void DeleteNFL_userPick(NFL_userPick instance);
    partial void InsertNFL_division(NFL_division instance);
    partial void UpdateNFL_division(NFL_division instance);
    partial void DeleteNFL_division(NFL_division instance);
    partial void InsertvisitorRequestLog(visitorRequestLog instance);
    partial void UpdatevisitorRequestLog(visitorRequestLog instance);
    partial void DeletevisitorRequestLog(visitorRequestLog instance);
    partial void InsertuserSetting(userSetting instance);
    partial void UpdateuserSetting(userSetting instance);
    partial void DeleteuserSetting(userSetting instance);
    partial void InsertNFL_Matchup(NFL_Matchup instance);
    partial void UpdateNFL_Matchup(NFL_Matchup instance);
    partial void DeleteNFL_Matchup(NFL_Matchup instance);
    partial void InsertNFL_week(NFL_week instance);
    partial void UpdateNFL_week(NFL_week instance);
    partial void DeleteNFL_week(NFL_week instance);
    partial void InsertemailSubscriptionType(emailSubscriptionType instance);
    partial void UpdateemailSubscriptionType(emailSubscriptionType instance);
    partial void DeleteemailSubscriptionType(emailSubscriptionType instance);
    partial void InsertNFL_sport(NFL_sport instance);
    partial void UpdateNFL_sport(NFL_sport instance);
    partial void DeleteNFL_sport(NFL_sport instance);
    partial void InsertNFL_team(NFL_team instance);
    partial void UpdateNFL_team(NFL_team instance);
    partial void DeleteNFL_team(NFL_team instance);
    partial void Insertuser(user instance);
    partial void Updateuser(user instance);
    partial void Deleteuser(user instance);
    partial void InsertNFL_year(NFL_year instance);
    partial void UpdateNFL_year(NFL_year instance);
    partial void DeleteNFL_year(NFL_year instance);
    #endregion
		
		public DBModelDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HomeWebAppDBConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<visitor> visitors
		{
			get
			{
				return this.GetTable<visitor>();
			}
		}
		
		public System.Data.Linq.Table<visitorCustomMessageHistory> visitorCustomMessageHistories
		{
			get
			{
				return this.GetTable<visitorCustomMessageHistory>();
			}
		}
		
		public System.Data.Linq.Table<usersToVisitor> usersToVisitors
		{
			get
			{
				return this.GetTable<usersToVisitor>();
			}
		}
		
		public System.Data.Linq.Table<NFL_userPick> NFL_userPicks
		{
			get
			{
				return this.GetTable<NFL_userPick>();
			}
		}
		
		public System.Data.Linq.Table<NFL_division> NFL_divisions
		{
			get
			{
				return this.GetTable<NFL_division>();
			}
		}
		
		public System.Data.Linq.Table<visitorRequestLog> visitorRequestLogs
		{
			get
			{
				return this.GetTable<visitorRequestLog>();
			}
		}
		
		public System.Data.Linq.Table<userSetting> userSettings
		{
			get
			{
				return this.GetTable<userSetting>();
			}
		}
		
		public System.Data.Linq.Table<NFL_WeekType> NFL_WeekTypes
		{
			get
			{
				return this.GetTable<NFL_WeekType>();
			}
		}
		
		public System.Data.Linq.Table<NFL_Matchup> NFL_Matchups
		{
			get
			{
				return this.GetTable<NFL_Matchup>();
			}
		}
		
		public System.Data.Linq.Table<NFL_week> NFL_weeks
		{
			get
			{
				return this.GetTable<NFL_week>();
			}
		}
		
		public System.Data.Linq.Table<emailSubscriptionType> emailSubscriptionTypes
		{
			get
			{
				return this.GetTable<emailSubscriptionType>();
			}
		}
		
		public System.Data.Linq.Table<NFL_sport> NFL_sports
		{
			get
			{
				return this.GetTable<NFL_sport>();
			}
		}
		
		public System.Data.Linq.Table<NFL_team> NFL_teams
		{
			get
			{
				return this.GetTable<NFL_team>();
			}
		}
		
		public System.Data.Linq.Table<user> users
		{
			get
			{
				return this.GetTable<user>();
			}
		}
		
		public System.Data.Linq.Table<NFL_year> NFL_years
		{
			get
			{
				return this.GetTable<NFL_year>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.visitors")]
	public partial class visitor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ip_address;
		
		private string _city;
		
		private string _region;
		
		private string _country;
		
		private string _zip;
		
		private string _coordinates;
		
		private string _ISP;
		
		private string _details_html;
		
		private System.Nullable<System.DateTime> _first_request_dt;
		
		private string _message;
		
		private EntitySet<visitorCustomMessageHistory> _visitorCustomMessageHistories;
		
		private EntitySet<visitorRequestLog> _visitorRequestLogs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onip_addressChanging(string value);
    partial void Onip_addressChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnregionChanging(string value);
    partial void OnregionChanged();
    partial void OncountryChanging(string value);
    partial void OncountryChanged();
    partial void OnzipChanging(string value);
    partial void OnzipChanged();
    partial void OncoordinatesChanging(string value);
    partial void OncoordinatesChanged();
    partial void OnISPChanging(string value);
    partial void OnISPChanged();
    partial void Ondetails_htmlChanging(string value);
    partial void Ondetails_htmlChanged();
    partial void Onfirst_request_dtChanging(System.Nullable<System.DateTime> value);
    partial void Onfirst_request_dtChanged();
    partial void OnmessageChanging(string value);
    partial void OnmessageChanged();
    #endregion
		
		public visitor()
		{
			this._visitorCustomMessageHistories = new EntitySet<visitorCustomMessageHistory>(new Action<visitorCustomMessageHistory>(this.attach_visitorCustomMessageHistories), new Action<visitorCustomMessageHistory>(this.detach_visitorCustomMessageHistories));
			this._visitorRequestLogs = new EntitySet<visitorRequestLog>(new Action<visitorRequestLog>(this.attach_visitorRequestLogs), new Action<visitorRequestLog>(this.detach_visitorRequestLogs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ip_address", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ip_address
		{
			get
			{
				return this._ip_address;
			}
			set
			{
				if ((this._ip_address != value))
				{
					this.Onip_addressChanging(value);
					this.SendPropertyChanging();
					this._ip_address = value;
					this.SendPropertyChanged("ip_address");
					this.Onip_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(50)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_region", DbType="VarChar(50)")]
		public string region
		{
			get
			{
				return this._region;
			}
			set
			{
				if ((this._region != value))
				{
					this.OnregionChanging(value);
					this.SendPropertyChanging();
					this._region = value;
					this.SendPropertyChanged("region");
					this.OnregionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="VarChar(50)")]
		public string country
		{
			get
			{
				return this._country;
			}
			set
			{
				if ((this._country != value))
				{
					this.OncountryChanging(value);
					this.SendPropertyChanging();
					this._country = value;
					this.SendPropertyChanged("country");
					this.OncountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zip", DbType="VarChar(10)")]
		public string zip
		{
			get
			{
				return this._zip;
			}
			set
			{
				if ((this._zip != value))
				{
					this.OnzipChanging(value);
					this.SendPropertyChanging();
					this._zip = value;
					this.SendPropertyChanged("zip");
					this.OnzipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_coordinates", DbType="VarChar(50)")]
		public string coordinates
		{
			get
			{
				return this._coordinates;
			}
			set
			{
				if ((this._coordinates != value))
				{
					this.OncoordinatesChanging(value);
					this.SendPropertyChanging();
					this._coordinates = value;
					this.SendPropertyChanged("coordinates");
					this.OncoordinatesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISP", DbType="VarChar(50)")]
		public string ISP
		{
			get
			{
				return this._ISP;
			}
			set
			{
				if ((this._ISP != value))
				{
					this.OnISPChanging(value);
					this.SendPropertyChanging();
					this._ISP = value;
					this.SendPropertyChanged("ISP");
					this.OnISPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_details_html", DbType="VarChar(MAX)")]
		public string details_html
		{
			get
			{
				return this._details_html;
			}
			set
			{
				if ((this._details_html != value))
				{
					this.Ondetails_htmlChanging(value);
					this.SendPropertyChanging();
					this._details_html = value;
					this.SendPropertyChanged("details_html");
					this.Ondetails_htmlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_first_request_dt", DbType="DateTime")]
		public System.Nullable<System.DateTime> first_request_dt
		{
			get
			{
				return this._first_request_dt;
			}
			set
			{
				if ((this._first_request_dt != value))
				{
					this.Onfirst_request_dtChanging(value);
					this.SendPropertyChanging();
					this._first_request_dt = value;
					this.SendPropertyChanged("first_request_dt");
					this.Onfirst_request_dtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_message", DbType="VarChar(MAX)")]
		public string message
		{
			get
			{
				return this._message;
			}
			set
			{
				if ((this._message != value))
				{
					this.OnmessageChanging(value);
					this.SendPropertyChanging();
					this._message = value;
					this.SendPropertyChanged("message");
					this.OnmessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="visitor_visitorCustomMessageHistory", Storage="_visitorCustomMessageHistories", ThisKey="ip_address", OtherKey="ip_address")]
		public EntitySet<visitorCustomMessageHistory> visitorCustomMessageHistories
		{
			get
			{
				return this._visitorCustomMessageHistories;
			}
			set
			{
				this._visitorCustomMessageHistories.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="visitor_visitorRequestLog", Storage="_visitorRequestLogs", ThisKey="ip_address", OtherKey="ip_address")]
		public EntitySet<visitorRequestLog> visitorRequestLogs
		{
			get
			{
				return this._visitorRequestLogs;
			}
			set
			{
				this._visitorRequestLogs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_visitorCustomMessageHistories(visitorCustomMessageHistory entity)
		{
			this.SendPropertyChanging();
			entity.visitor = this;
		}
		
		private void detach_visitorCustomMessageHistories(visitorCustomMessageHistory entity)
		{
			this.SendPropertyChanging();
			entity.visitor = null;
		}
		
		private void attach_visitorRequestLogs(visitorRequestLog entity)
		{
			this.SendPropertyChanging();
			entity.visitor = this;
		}
		
		private void detach_visitorRequestLogs(visitorRequestLog entity)
		{
			this.SendPropertyChanging();
			entity.visitor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.visitorCustomMessageHistory")]
	public partial class visitorCustomMessageHistory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ip_address;
		
		private string _message;
		
		private System.Nullable<System.DateTime> _update_dt;
		
		private EntityRef<visitor> _visitor;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onip_addressChanging(string value);
    partial void Onip_addressChanged();
    partial void OnmessageChanging(string value);
    partial void OnmessageChanged();
    partial void Onupdate_dtChanging(System.Nullable<System.DateTime> value);
    partial void Onupdate_dtChanged();
    #endregion
		
		public visitorCustomMessageHistory()
		{
			this._visitor = default(EntityRef<visitor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ip_address", DbType="VarChar(50)")]
		public string ip_address
		{
			get
			{
				return this._ip_address;
			}
			set
			{
				if ((this._ip_address != value))
				{
					if (this._visitor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onip_addressChanging(value);
					this.SendPropertyChanging();
					this._ip_address = value;
					this.SendPropertyChanged("ip_address");
					this.Onip_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_message", DbType="VarChar(MAX)")]
		public string message
		{
			get
			{
				return this._message;
			}
			set
			{
				if ((this._message != value))
				{
					this.OnmessageChanging(value);
					this.SendPropertyChanging();
					this._message = value;
					this.SendPropertyChanged("message");
					this.OnmessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_dt", DbType="DateTime")]
		public System.Nullable<System.DateTime> update_dt
		{
			get
			{
				return this._update_dt;
			}
			set
			{
				if ((this._update_dt != value))
				{
					this.Onupdate_dtChanging(value);
					this.SendPropertyChanging();
					this._update_dt = value;
					this.SendPropertyChanged("update_dt");
					this.Onupdate_dtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="visitor_visitorCustomMessageHistory", Storage="_visitor", ThisKey="ip_address", OtherKey="ip_address", IsForeignKey=true)]
		public visitor visitor
		{
			get
			{
				return this._visitor.Entity;
			}
			set
			{
				visitor previousValue = this._visitor.Entity;
				if (((previousValue != value) 
							|| (this._visitor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._visitor.Entity = null;
						previousValue.visitorCustomMessageHistories.Remove(this);
					}
					this._visitor.Entity = value;
					if ((value != null))
					{
						value.visitorCustomMessageHistories.Add(this);
						this._ip_address = value.ip_address;
					}
					else
					{
						this._ip_address = default(string);
					}
					this.SendPropertyChanged("visitor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usersToVisitors")]
	public partial class usersToVisitor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _username;
		
		private string _ip_address;
		
		private System.DateTime _insert_dt;
		
		private int _id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void Onip_addressChanging(string value);
    partial void Onip_addressChanged();
    partial void Oninsert_dtChanging(System.DateTime value);
    partial void Oninsert_dtChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    #endregion
		
		public usersToVisitor()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ip_address", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ip_address
		{
			get
			{
				return this._ip_address;
			}
			set
			{
				if ((this._ip_address != value))
				{
					this.Onip_addressChanging(value);
					this.SendPropertyChanging();
					this._ip_address = value;
					this.SendPropertyChanged("ip_address");
					this.Onip_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insert_dt", DbType="DateTime NOT NULL")]
		public System.DateTime insert_dt
		{
			get
			{
				return this._insert_dt;
			}
			set
			{
				if ((this._insert_dt != value))
				{
					this.Oninsert_dtChanging(value);
					this.SendPropertyChanging();
					this._insert_dt = value;
					this.SendPropertyChanged("insert_dt");
					this.Oninsert_dtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NFL_userPicks")]
	public partial class NFL_userPick : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _username;
		
		private int _week;
		
		private string _picks;
		
		private System.DateTime _pick_dt;
		
		private EntityRef<NFL_week> _NFL_week;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnweekChanging(int value);
    partial void OnweekChanged();
    partial void OnpicksChanging(string value);
    partial void OnpicksChanged();
    partial void Onpick_dtChanging(System.DateTime value);
    partial void Onpick_dtChanged();
    #endregion
		
		public NFL_userPick()
		{
			this._NFL_week = default(EntityRef<NFL_week>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_week", DbType="Int NOT NULL")]
		public int week
		{
			get
			{
				return this._week;
			}
			set
			{
				if ((this._week != value))
				{
					if (this._NFL_week.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnweekChanging(value);
					this.SendPropertyChanging();
					this._week = value;
					this.SendPropertyChanged("week");
					this.OnweekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_picks", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string picks
		{
			get
			{
				return this._picks;
			}
			set
			{
				if ((this._picks != value))
				{
					this.OnpicksChanging(value);
					this.SendPropertyChanging();
					this._picks = value;
					this.SendPropertyChanged("picks");
					this.OnpicksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pick_dt", DbType="DateTime NOT NULL")]
		public System.DateTime pick_dt
		{
			get
			{
				return this._pick_dt;
			}
			set
			{
				if ((this._pick_dt != value))
				{
					this.Onpick_dtChanging(value);
					this.SendPropertyChanging();
					this._pick_dt = value;
					this.SendPropertyChanged("pick_dt");
					this.Onpick_dtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NFL_week_NFL_userPick", Storage="_NFL_week", ThisKey="week", OtherKey="week", IsForeignKey=true)]
		public NFL_week NFL_week
		{
			get
			{
				return this._NFL_week.Entity;
			}
			set
			{
				NFL_week previousValue = this._NFL_week.Entity;
				if (((previousValue != value) 
							|| (this._NFL_week.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NFL_week.Entity = null;
						previousValue.NFL_userPicks.Remove(this);
					}
					this._NFL_week.Entity = value;
					if ((value != null))
					{
						value.NFL_userPicks.Add(this);
						this._week = value.week;
					}
					else
					{
						this._week = default(int);
					}
					this.SendPropertyChanged("NFL_week");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NFL_divisions")]
	public partial class NFL_division : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    #endregion
		
		public NFL_division()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(50)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.visitorRequestLog")]
	public partial class visitorRequestLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ip_address;
		
		private string _request_page;
		
		private string _request_url;
		
		private System.Nullable<System.DateTime> _request_datetime;
		
		private string _username;
		
		private string _control_desc;
		
		private EntityRef<visitor> _visitor;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onip_addressChanging(string value);
    partial void Onip_addressChanged();
    partial void Onrequest_pageChanging(string value);
    partial void Onrequest_pageChanged();
    partial void Onrequest_urlChanging(string value);
    partial void Onrequest_urlChanged();
    partial void Onrequest_datetimeChanging(System.Nullable<System.DateTime> value);
    partial void Onrequest_datetimeChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void Oncontrol_descChanging(string value);
    partial void Oncontrol_descChanged();
    #endregion
		
		public visitorRequestLog()
		{
			this._visitor = default(EntityRef<visitor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ip_address", DbType="VarChar(50)")]
		public string ip_address
		{
			get
			{
				return this._ip_address;
			}
			set
			{
				if ((this._ip_address != value))
				{
					if (this._visitor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onip_addressChanging(value);
					this.SendPropertyChanging();
					this._ip_address = value;
					this.SendPropertyChanged("ip_address");
					this.Onip_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_request_page", DbType="VarChar(50)")]
		public string request_page
		{
			get
			{
				return this._request_page;
			}
			set
			{
				if ((this._request_page != value))
				{
					this.Onrequest_pageChanging(value);
					this.SendPropertyChanging();
					this._request_page = value;
					this.SendPropertyChanged("request_page");
					this.Onrequest_pageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_request_url", DbType="VarChar(MAX)")]
		public string request_url
		{
			get
			{
				return this._request_url;
			}
			set
			{
				if ((this._request_url != value))
				{
					this.Onrequest_urlChanging(value);
					this.SendPropertyChanging();
					this._request_url = value;
					this.SendPropertyChanged("request_url");
					this.Onrequest_urlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_request_datetime", DbType="DateTime")]
		public System.Nullable<System.DateTime> request_datetime
		{
			get
			{
				return this._request_datetime;
			}
			set
			{
				if ((this._request_datetime != value))
				{
					this.Onrequest_datetimeChanging(value);
					this.SendPropertyChanging();
					this._request_datetime = value;
					this.SendPropertyChanged("request_datetime");
					this.Onrequest_datetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_control_desc", DbType="VarChar(50)")]
		public string control_desc
		{
			get
			{
				return this._control_desc;
			}
			set
			{
				if ((this._control_desc != value))
				{
					this.Oncontrol_descChanging(value);
					this.SendPropertyChanging();
					this._control_desc = value;
					this.SendPropertyChanged("control_desc");
					this.Oncontrol_descChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="visitor_visitorRequestLog", Storage="_visitor", ThisKey="ip_address", OtherKey="ip_address", IsForeignKey=true)]
		public visitor visitor
		{
			get
			{
				return this._visitor.Entity;
			}
			set
			{
				visitor previousValue = this._visitor.Entity;
				if (((previousValue != value) 
							|| (this._visitor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._visitor.Entity = null;
						previousValue.visitorRequestLogs.Remove(this);
					}
					this._visitor.Entity = value;
					if ((value != null))
					{
						value.visitorRequestLogs.Add(this);
						this._ip_address = value.ip_address;
					}
					else
					{
						this._ip_address = default(string);
					}
					this.SendPropertyChanged("visitor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.userSettings")]
	public partial class userSetting : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _username;
		
		private string _settingKey;
		
		private string _settingValue;
		
		private System.DateTime _insert_dt;
		
		private System.DateTime _update_dt;
		
		private bool _active_flag;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnsettingKeyChanging(string value);
    partial void OnsettingKeyChanged();
    partial void OnsettingValueChanging(string value);
    partial void OnsettingValueChanged();
    partial void Oninsert_dtChanging(System.DateTime value);
    partial void Oninsert_dtChanged();
    partial void Onupdate_dtChanging(System.DateTime value);
    partial void Onupdate_dtChanged();
    partial void Onactive_flagChanging(bool value);
    partial void Onactive_flagChanged();
    #endregion
		
		public userSetting()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_settingKey", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string settingKey
		{
			get
			{
				return this._settingKey;
			}
			set
			{
				if ((this._settingKey != value))
				{
					this.OnsettingKeyChanging(value);
					this.SendPropertyChanging();
					this._settingKey = value;
					this.SendPropertyChanged("settingKey");
					this.OnsettingKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_settingValue", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string settingValue
		{
			get
			{
				return this._settingValue;
			}
			set
			{
				if ((this._settingValue != value))
				{
					this.OnsettingValueChanging(value);
					this.SendPropertyChanging();
					this._settingValue = value;
					this.SendPropertyChanged("settingValue");
					this.OnsettingValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insert_dt", DbType="DateTime NOT NULL")]
		public System.DateTime insert_dt
		{
			get
			{
				return this._insert_dt;
			}
			set
			{
				if ((this._insert_dt != value))
				{
					this.Oninsert_dtChanging(value);
					this.SendPropertyChanging();
					this._insert_dt = value;
					this.SendPropertyChanged("insert_dt");
					this.Oninsert_dtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_dt", DbType="DateTime NOT NULL")]
		public System.DateTime update_dt
		{
			get
			{
				return this._update_dt;
			}
			set
			{
				if ((this._update_dt != value))
				{
					this.Onupdate_dtChanging(value);
					this.SendPropertyChanging();
					this._update_dt = value;
					this.SendPropertyChanged("update_dt");
					this.Onupdate_dtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active_flag", DbType="Bit NOT NULL")]
		public bool active_flag
		{
			get
			{
				return this._active_flag;
			}
			set
			{
				if ((this._active_flag != value))
				{
					this.Onactive_flagChanging(value);
					this.SendPropertyChanging();
					this._active_flag = value;
					this.SendPropertyChanged("active_flag");
					this.Onactive_flagChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NFL_WeekTypes")]
	public partial class NFL_WeekType
	{
		
		private int _id;
		
		private string _name;
		
		public NFL_WeekType()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NFL_Matchups")]
	public partial class NFL_Matchup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _week;
		
		private string _away;
		
		private string _home;
		
		private string _winner;
		
		private System.Nullable<int> _home_score;
		
		private System.Nullable<int> _away_score;
		
		private string _status;
		
		private string _scheduled;
		
		private System.Nullable<long> _eid;
		
		private System.Nullable<int> _year_week;
		
		private EntityRef<NFL_week> _NFL_week;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnweekChanging(int value);
    partial void OnweekChanged();
    partial void OnawayChanging(string value);
    partial void OnawayChanged();
    partial void OnhomeChanging(string value);
    partial void OnhomeChanged();
    partial void OnwinnerChanging(string value);
    partial void OnwinnerChanged();
    partial void Onhome_scoreChanging(System.Nullable<int> value);
    partial void Onhome_scoreChanged();
    partial void Onaway_scoreChanging(System.Nullable<int> value);
    partial void Onaway_scoreChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OnscheduledChanging(string value);
    partial void OnscheduledChanged();
    partial void OneidChanging(System.Nullable<long> value);
    partial void OneidChanged();
    partial void Onyear_weekChanging(System.Nullable<int> value);
    partial void Onyear_weekChanged();
    #endregion
		
		public NFL_Matchup()
		{
			this._NFL_week = default(EntityRef<NFL_week>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_week", DbType="Int NOT NULL")]
		public int week
		{
			get
			{
				return this._week;
			}
			set
			{
				if ((this._week != value))
				{
					if (this._NFL_week.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnweekChanging(value);
					this.SendPropertyChanging();
					this._week = value;
					this.SendPropertyChanged("week");
					this.OnweekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_away", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string away
		{
			get
			{
				return this._away;
			}
			set
			{
				if ((this._away != value))
				{
					this.OnawayChanging(value);
					this.SendPropertyChanging();
					this._away = value;
					this.SendPropertyChanged("away");
					this.OnawayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_home", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string home
		{
			get
			{
				return this._home;
			}
			set
			{
				if ((this._home != value))
				{
					this.OnhomeChanging(value);
					this.SendPropertyChanging();
					this._home = value;
					this.SendPropertyChanged("home");
					this.OnhomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_winner", DbType="VarChar(50)")]
		public string winner
		{
			get
			{
				return this._winner;
			}
			set
			{
				if ((this._winner != value))
				{
					this.OnwinnerChanging(value);
					this.SendPropertyChanging();
					this._winner = value;
					this.SendPropertyChanged("winner");
					this.OnwinnerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_home_score", DbType="Int")]
		public System.Nullable<int> home_score
		{
			get
			{
				return this._home_score;
			}
			set
			{
				if ((this._home_score != value))
				{
					this.Onhome_scoreChanging(value);
					this.SendPropertyChanging();
					this._home_score = value;
					this.SendPropertyChanged("home_score");
					this.Onhome_scoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_away_score", DbType="Int")]
		public System.Nullable<int> away_score
		{
			get
			{
				return this._away_score;
			}
			set
			{
				if ((this._away_score != value))
				{
					this.Onaway_scoreChanging(value);
					this.SendPropertyChanging();
					this._away_score = value;
					this.SendPropertyChanged("away_score");
					this.Onaway_scoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(5)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scheduled", DbType="VarChar(20)")]
		public string scheduled
		{
			get
			{
				return this._scheduled;
			}
			set
			{
				if ((this._scheduled != value))
				{
					this.OnscheduledChanging(value);
					this.SendPropertyChanging();
					this._scheduled = value;
					this.SendPropertyChanged("scheduled");
					this.OnscheduledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eid", DbType="BigInt")]
		public System.Nullable<long> eid
		{
			get
			{
				return this._eid;
			}
			set
			{
				if ((this._eid != value))
				{
					this.OneidChanging(value);
					this.SendPropertyChanging();
					this._eid = value;
					this.SendPropertyChanged("eid");
					this.OneidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_year_week", DbType="Int")]
		public System.Nullable<int> year_week
		{
			get
			{
				return this._year_week;
			}
			set
			{
				if ((this._year_week != value))
				{
					this.Onyear_weekChanging(value);
					this.SendPropertyChanging();
					this._year_week = value;
					this.SendPropertyChanged("year_week");
					this.Onyear_weekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NFL_week_NFL_Matchup", Storage="_NFL_week", ThisKey="week", OtherKey="week", IsForeignKey=true)]
		public NFL_week NFL_week
		{
			get
			{
				return this._NFL_week.Entity;
			}
			set
			{
				NFL_week previousValue = this._NFL_week.Entity;
				if (((previousValue != value) 
							|| (this._NFL_week.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NFL_week.Entity = null;
						previousValue.NFL_Matchups.Remove(this);
					}
					this._NFL_week.Entity = value;
					if ((value != null))
					{
						value.NFL_Matchups.Add(this);
						this._week = value.week;
					}
					else
					{
						this._week = default(int);
					}
					this.SendPropertyChanged("NFL_week");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NFL_weeks")]
	public partial class NFL_week : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _week;
		
		private System.DateTime _exp_dt;
		
		private System.Nullable<int> _games;
		
		private string _text;
		
		private System.Nullable<int> _year_id;
		
		private System.Nullable<int> _year_week;
		
		private System.Nullable<int> _sort_id;
		
		private System.Nullable<int> _weekTypeId;
		
		private bool _display_flag;
		
		private bool _picksClosed;
		
		private EntitySet<NFL_userPick> _NFL_userPicks;
		
		private EntitySet<NFL_Matchup> _NFL_Matchups;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnweekChanging(int value);
    partial void OnweekChanged();
    partial void Onexp_dtChanging(System.DateTime value);
    partial void Onexp_dtChanged();
    partial void OngamesChanging(System.Nullable<int> value);
    partial void OngamesChanged();
    partial void OntextChanging(string value);
    partial void OntextChanged();
    partial void Onyear_idChanging(System.Nullable<int> value);
    partial void Onyear_idChanged();
    partial void Onyear_weekChanging(System.Nullable<int> value);
    partial void Onyear_weekChanged();
    partial void Onsort_idChanging(System.Nullable<int> value);
    partial void Onsort_idChanged();
    partial void OnweekTypeIdChanging(System.Nullable<int> value);
    partial void OnweekTypeIdChanged();
    partial void Ondisplay_flagChanging(bool value);
    partial void Ondisplay_flagChanged();
    partial void OnpicksClosedChanging(bool value);
    partial void OnpicksClosedChanged();
    #endregion
		
		public NFL_week()
		{
			this._NFL_userPicks = new EntitySet<NFL_userPick>(new Action<NFL_userPick>(this.attach_NFL_userPicks), new Action<NFL_userPick>(this.detach_NFL_userPicks));
			this._NFL_Matchups = new EntitySet<NFL_Matchup>(new Action<NFL_Matchup>(this.attach_NFL_Matchups), new Action<NFL_Matchup>(this.detach_NFL_Matchups));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_week", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int week
		{
			get
			{
				return this._week;
			}
			set
			{
				if ((this._week != value))
				{
					this.OnweekChanging(value);
					this.SendPropertyChanging();
					this._week = value;
					this.SendPropertyChanged("week");
					this.OnweekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exp_dt", DbType="DateTime NOT NULL")]
		public System.DateTime exp_dt
		{
			get
			{
				return this._exp_dt;
			}
			set
			{
				if ((this._exp_dt != value))
				{
					this.Onexp_dtChanging(value);
					this.SendPropertyChanging();
					this._exp_dt = value;
					this.SendPropertyChanged("exp_dt");
					this.Onexp_dtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_games", DbType="Int")]
		public System.Nullable<int> games
		{
			get
			{
				return this._games;
			}
			set
			{
				if ((this._games != value))
				{
					this.OngamesChanging(value);
					this.SendPropertyChanging();
					this._games = value;
					this.SendPropertyChanged("games");
					this.OngamesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_text", DbType="VarChar(50)")]
		public string text
		{
			get
			{
				return this._text;
			}
			set
			{
				if ((this._text != value))
				{
					this.OntextChanging(value);
					this.SendPropertyChanging();
					this._text = value;
					this.SendPropertyChanged("text");
					this.OntextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_year_id", DbType="Int")]
		public System.Nullable<int> year_id
		{
			get
			{
				return this._year_id;
			}
			set
			{
				if ((this._year_id != value))
				{
					this.Onyear_idChanging(value);
					this.SendPropertyChanging();
					this._year_id = value;
					this.SendPropertyChanged("year_id");
					this.Onyear_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_year_week", DbType="Int")]
		public System.Nullable<int> year_week
		{
			get
			{
				return this._year_week;
			}
			set
			{
				if ((this._year_week != value))
				{
					this.Onyear_weekChanging(value);
					this.SendPropertyChanging();
					this._year_week = value;
					this.SendPropertyChanged("year_week");
					this.Onyear_weekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sort_id", DbType="Int")]
		public System.Nullable<int> sort_id
		{
			get
			{
				return this._sort_id;
			}
			set
			{
				if ((this._sort_id != value))
				{
					this.Onsort_idChanging(value);
					this.SendPropertyChanging();
					this._sort_id = value;
					this.SendPropertyChanged("sort_id");
					this.Onsort_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weekTypeId", DbType="Int")]
		public System.Nullable<int> weekTypeId
		{
			get
			{
				return this._weekTypeId;
			}
			set
			{
				if ((this._weekTypeId != value))
				{
					this.OnweekTypeIdChanging(value);
					this.SendPropertyChanging();
					this._weekTypeId = value;
					this.SendPropertyChanged("weekTypeId");
					this.OnweekTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_display_flag", DbType="Bit NOT NULL")]
		public bool display_flag
		{
			get
			{
				return this._display_flag;
			}
			set
			{
				if ((this._display_flag != value))
				{
					this.Ondisplay_flagChanging(value);
					this.SendPropertyChanging();
					this._display_flag = value;
					this.SendPropertyChanged("display_flag");
					this.Ondisplay_flagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_picksClosed", DbType="Bit NOT NULL")]
		public bool picksClosed
		{
			get
			{
				return this._picksClosed;
			}
			set
			{
				if ((this._picksClosed != value))
				{
					this.OnpicksClosedChanging(value);
					this.SendPropertyChanging();
					this._picksClosed = value;
					this.SendPropertyChanged("picksClosed");
					this.OnpicksClosedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NFL_week_NFL_userPick", Storage="_NFL_userPicks", ThisKey="week", OtherKey="week")]
		public EntitySet<NFL_userPick> NFL_userPicks
		{
			get
			{
				return this._NFL_userPicks;
			}
			set
			{
				this._NFL_userPicks.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NFL_week_NFL_Matchup", Storage="_NFL_Matchups", ThisKey="week", OtherKey="week")]
		public EntitySet<NFL_Matchup> NFL_Matchups
		{
			get
			{
				return this._NFL_Matchups;
			}
			set
			{
				this._NFL_Matchups.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NFL_userPicks(NFL_userPick entity)
		{
			this.SendPropertyChanging();
			entity.NFL_week = this;
		}
		
		private void detach_NFL_userPicks(NFL_userPick entity)
		{
			this.SendPropertyChanging();
			entity.NFL_week = null;
		}
		
		private void attach_NFL_Matchups(NFL_Matchup entity)
		{
			this.SendPropertyChanging();
			entity.NFL_week = this;
		}
		
		private void detach_NFL_Matchups(NFL_Matchup entity)
		{
			this.SendPropertyChanging();
			entity.NFL_week = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.emailSubscriptionTypes")]
	public partial class emailSubscriptionType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public emailSubscriptionType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NFL_sports")]
	public partial class NFL_sport : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public NFL_sport()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NFL_teams")]
	public partial class NFL_team : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _location;
		
		private string _name;
		
		private string _division;
		
		private int _sport_id;
		
		private bool _display_flag;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnlocationChanging(string value);
    partial void OnlocationChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OndivisionChanging(string value);
    partial void OndivisionChanged();
    partial void Onsport_idChanging(int value);
    partial void Onsport_idChanged();
    partial void Ondisplay_flagChanging(bool value);
    partial void Ondisplay_flagChanged();
    #endregion
		
		public NFL_team()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="VarChar(50)")]
		public string location
		{
			get
			{
				return this._location;
			}
			set
			{
				if ((this._location != value))
				{
					this.OnlocationChanging(value);
					this.SendPropertyChanging();
					this._location = value;
					this.SendPropertyChanged("location");
					this.OnlocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_division", DbType="VarChar(50)")]
		public string division
		{
			get
			{
				return this._division;
			}
			set
			{
				if ((this._division != value))
				{
					this.OndivisionChanging(value);
					this.SendPropertyChanging();
					this._division = value;
					this.SendPropertyChanged("division");
					this.OndivisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sport_id", DbType="Int NOT NULL")]
		public int sport_id
		{
			get
			{
				return this._sport_id;
			}
			set
			{
				if ((this._sport_id != value))
				{
					this.Onsport_idChanging(value);
					this.SendPropertyChanging();
					this._sport_id = value;
					this.SendPropertyChanged("sport_id");
					this.Onsport_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_display_flag", DbType="Bit NOT NULL")]
		public bool display_flag
		{
			get
			{
				return this._display_flag;
			}
			set
			{
				if ((this._display_flag != value))
				{
					this.Ondisplay_flagChanging(value);
					this.SendPropertyChanging();
					this._display_flag = value;
					this.SendPropertyChanged("display_flag");
					this.Ondisplay_flagChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.users")]
	public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _name;
		
		private string _encPW;
		
		private string _ip_address;
		
		private System.Nullable<System.DateTime> _registration_dt;
		
		private string _email;
		
		private System.Nullable<System.DateTime> _stay_logged_on_dt;
		
		private System.Nullable<System.DateTime> _birthday;
		
		private bool _IsActive;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnencPWChanging(string value);
    partial void OnencPWChanged();
    partial void Onip_addressChanging(string value);
    partial void Onip_addressChanged();
    partial void Onregistration_dtChanging(System.Nullable<System.DateTime> value);
    partial void Onregistration_dtChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onstay_logged_on_dtChanging(System.Nullable<System.DateTime> value);
    partial void Onstay_logged_on_dtChanged();
    partial void OnbirthdayChanging(System.Nullable<System.DateTime> value);
    partial void OnbirthdayChanged();
    partial void OnIsActiveChanging(bool value);
    partial void OnIsActiveChanged();
    #endregion
		
		public user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_encPW", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string encPW
		{
			get
			{
				return this._encPW;
			}
			set
			{
				if ((this._encPW != value))
				{
					this.OnencPWChanging(value);
					this.SendPropertyChanging();
					this._encPW = value;
					this.SendPropertyChanged("encPW");
					this.OnencPWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ip_address", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ip_address
		{
			get
			{
				return this._ip_address;
			}
			set
			{
				if ((this._ip_address != value))
				{
					this.Onip_addressChanging(value);
					this.SendPropertyChanging();
					this._ip_address = value;
					this.SendPropertyChanged("ip_address");
					this.Onip_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_registration_dt", DbType="DateTime")]
		public System.Nullable<System.DateTime> registration_dt
		{
			get
			{
				return this._registration_dt;
			}
			set
			{
				if ((this._registration_dt != value))
				{
					this.Onregistration_dtChanging(value);
					this.SendPropertyChanging();
					this._registration_dt = value;
					this.SendPropertyChanged("registration_dt");
					this.Onregistration_dtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stay_logged_on_dt", DbType="DateTime")]
		public System.Nullable<System.DateTime> stay_logged_on_dt
		{
			get
			{
				return this._stay_logged_on_dt;
			}
			set
			{
				if ((this._stay_logged_on_dt != value))
				{
					this.Onstay_logged_on_dtChanging(value);
					this.SendPropertyChanging();
					this._stay_logged_on_dt = value;
					this.SendPropertyChanged("stay_logged_on_dt");
					this.Onstay_logged_on_dtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthday", DbType="DateTime")]
		public System.Nullable<System.DateTime> birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if ((this._birthday != value))
				{
					this.OnbirthdayChanging(value);
					this.SendPropertyChanging();
					this._birthday = value;
					this.SendPropertyChanged("birthday");
					this.OnbirthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NFL_years")]
	public partial class NFL_year : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _text;
		
		private int _year;
		
		private int _sport_id;
		
		private System.Nullable<int> _betAmount;
		
		private string _betUsers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntextChanging(string value);
    partial void OntextChanged();
    partial void OnyearChanging(int value);
    partial void OnyearChanged();
    partial void Onsport_idChanging(int value);
    partial void Onsport_idChanged();
    partial void OnbetAmountChanging(System.Nullable<int> value);
    partial void OnbetAmountChanged();
    partial void OnbetUsersChanging(string value);
    partial void OnbetUsersChanged();
    #endregion
		
		public NFL_year()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_text", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string text
		{
			get
			{
				return this._text;
			}
			set
			{
				if ((this._text != value))
				{
					this.OntextChanging(value);
					this.SendPropertyChanging();
					this._text = value;
					this.SendPropertyChanged("text");
					this.OntextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_year", DbType="Int NOT NULL")]
		public int year
		{
			get
			{
				return this._year;
			}
			set
			{
				if ((this._year != value))
				{
					this.OnyearChanging(value);
					this.SendPropertyChanging();
					this._year = value;
					this.SendPropertyChanged("year");
					this.OnyearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sport_id", DbType="Int NOT NULL")]
		public int sport_id
		{
			get
			{
				return this._sport_id;
			}
			set
			{
				if ((this._sport_id != value))
				{
					this.Onsport_idChanging(value);
					this.SendPropertyChanging();
					this._sport_id = value;
					this.SendPropertyChanged("sport_id");
					this.Onsport_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_betAmount", DbType="Int")]
		public System.Nullable<int> betAmount
		{
			get
			{
				return this._betAmount;
			}
			set
			{
				if ((this._betAmount != value))
				{
					this.OnbetAmountChanging(value);
					this.SendPropertyChanging();
					this._betAmount = value;
					this.SendPropertyChanged("betAmount");
					this.OnbetAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_betUsers", DbType="VarChar(MAX)")]
		public string betUsers
		{
			get
			{
				return this._betUsers;
			}
			set
			{
				if ((this._betUsers != value))
				{
					this.OnbetUsersChanging(value);
					this.SendPropertyChanging();
					this._betUsers = value;
					this.SendPropertyChanged("betUsers");
					this.OnbetUsersChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
