#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeAppsLib.db
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HomeWebAppDB")]
	public partial class dataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertuserSetting(userSetting instance);
    partial void UpdateuserSetting(userSetting instance);
    partial void DeleteuserSetting(userSetting instance);
    partial void InsertNFL_week(NFL_week instance);
    partial void UpdateNFL_week(NFL_week instance);
    partial void DeleteNFL_week(NFL_week instance);
    partial void InsertNFL_userPick(NFL_userPick instance);
    partial void UpdateNFL_userPick(NFL_userPick instance);
    partial void DeleteNFL_userPick(NFL_userPick instance);
    partial void Insertlog(log instance);
    partial void Updatelog(log instance);
    partial void Deletelog(log instance);
    partial void InsertEmailLog(EmailLog instance);
    partial void UpdateEmailLog(EmailLog instance);
    partial void DeleteEmailLog(EmailLog instance);
    partial void InsertNFL_forum(NFL_forum instance);
    partial void UpdateNFL_forum(NFL_forum instance);
    partial void DeleteNFL_forum(NFL_forum instance);
    partial void InsertemailSubscriptionType(emailSubscriptionType instance);
    partial void UpdateemailSubscriptionType(emailSubscriptionType instance);
    partial void DeleteemailSubscriptionType(emailSubscriptionType instance);
    partial void Insertuser(user instance);
    partial void Updateuser(user instance);
    partial void Deleteuser(user instance);
    partial void InsertNFL_year(NFL_year instance);
    partial void UpdateNFL_year(NFL_year instance);
    partial void DeleteNFL_year(NFL_year instance);
    partial void InsertNFL_sport(NFL_sport instance);
    partial void UpdateNFL_sport(NFL_sport instance);
    partial void DeleteNFL_sport(NFL_sport instance);
    partial void InsertNFL_Matchup(NFL_Matchup instance);
    partial void UpdateNFL_Matchup(NFL_Matchup instance);
    partial void DeleteNFL_Matchup(NFL_Matchup instance);
    #endregion
		
		public dataDataContext() : 
				base(global::HomeAppsLib.Properties.Settings.Default.HomeWebAppDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<userSetting> userSettings
		{
			get
			{
				return this.GetTable<userSetting>();
			}
		}
		
		public System.Data.Linq.Table<NFL_week> NFL_weeks
		{
			get
			{
				return this.GetTable<NFL_week>();
			}
		}
		
		public System.Data.Linq.Table<NFL_userPick> NFL_userPicks
		{
			get
			{
				return this.GetTable<NFL_userPick>();
			}
		}
		
		public System.Data.Linq.Table<log> logs
		{
			get
			{
				return this.GetTable<log>();
			}
		}
		
		public System.Data.Linq.Table<EmailLog> EmailLogs
		{
			get
			{
				return this.GetTable<EmailLog>();
			}
		}
		
		public System.Data.Linq.Table<NFL_forum> NFL_forums
		{
			get
			{
				return this.GetTable<NFL_forum>();
			}
		}
		
		public System.Data.Linq.Table<emailSubscriptionType> emailSubscriptionTypes
		{
			get
			{
				return this.GetTable<emailSubscriptionType>();
			}
		}
		
		public System.Data.Linq.Table<user> users
		{
			get
			{
				return this.GetTable<user>();
			}
		}
		
		public System.Data.Linq.Table<NFL_year> NFL_years
		{
			get
			{
				return this.GetTable<NFL_year>();
			}
		}
		
		public System.Data.Linq.Table<NFL_sport> NFL_sports
		{
			get
			{
				return this.GetTable<NFL_sport>();
			}
		}
		
		public System.Data.Linq.Table<NFL_Matchup> NFL_Matchups
		{
			get
			{
				return this.GetTable<NFL_Matchup>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.userSettings")]
	public partial class userSetting : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _username;
		
		private string _settingKey;
		
		private string _settingValue;
		
		private System.DateTime _insert_dt;
		
		private System.DateTime _update_dt;
		
		private bool _active_flag;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnsettingKeyChanging(string value);
    partial void OnsettingKeyChanged();
    partial void OnsettingValueChanging(string value);
    partial void OnsettingValueChanged();
    partial void Oninsert_dtChanging(System.DateTime value);
    partial void Oninsert_dtChanged();
    partial void Onupdate_dtChanging(System.DateTime value);
    partial void Onupdate_dtChanged();
    partial void Onactive_flagChanging(bool value);
    partial void Onactive_flagChanged();
    #endregion
		
		public userSetting()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_settingKey", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string settingKey
		{
			get
			{
				return this._settingKey;
			}
			set
			{
				if ((this._settingKey != value))
				{
					this.OnsettingKeyChanging(value);
					this.SendPropertyChanging();
					this._settingKey = value;
					this.SendPropertyChanged("settingKey");
					this.OnsettingKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_settingValue", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string settingValue
		{
			get
			{
				return this._settingValue;
			}
			set
			{
				if ((this._settingValue != value))
				{
					this.OnsettingValueChanging(value);
					this.SendPropertyChanging();
					this._settingValue = value;
					this.SendPropertyChanged("settingValue");
					this.OnsettingValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insert_dt", DbType="DateTime NOT NULL")]
		public System.DateTime insert_dt
		{
			get
			{
				return this._insert_dt;
			}
			set
			{
				if ((this._insert_dt != value))
				{
					this.Oninsert_dtChanging(value);
					this.SendPropertyChanging();
					this._insert_dt = value;
					this.SendPropertyChanged("insert_dt");
					this.Oninsert_dtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_dt", DbType="DateTime NOT NULL")]
		public System.DateTime update_dt
		{
			get
			{
				return this._update_dt;
			}
			set
			{
				if ((this._update_dt != value))
				{
					this.Onupdate_dtChanging(value);
					this.SendPropertyChanging();
					this._update_dt = value;
					this.SendPropertyChanged("update_dt");
					this.Onupdate_dtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active_flag", DbType="Bit NOT NULL")]
		public bool active_flag
		{
			get
			{
				return this._active_flag;
			}
			set
			{
				if ((this._active_flag != value))
				{
					this.Onactive_flagChanging(value);
					this.SendPropertyChanging();
					this._active_flag = value;
					this.SendPropertyChanged("active_flag");
					this.Onactive_flagChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NFL_weeks")]
	public partial class NFL_week : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _week;
		
		private System.DateTime _exp_dt;
		
		private System.Nullable<int> _games;
		
		private string _text;
		
		private System.Nullable<int> _year_id;
		
		private System.Nullable<int> _year_week;
		
		private System.Nullable<int> _sort_id;
		
		private System.Nullable<int> _weekTypeId;
		
		private bool _display_flag;
		
		private bool _picksClosed;
		
		private EntitySet<NFL_forum> _NFL_forums;
		
		private EntitySet<NFL_Matchup> _NFL_Matchups;
		
		private EntityRef<NFL_year> _NFL_year;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnweekChanging(int value);
    partial void OnweekChanged();
    partial void Onexp_dtChanging(System.DateTime value);
    partial void Onexp_dtChanged();
    partial void OngamesChanging(System.Nullable<int> value);
    partial void OngamesChanged();
    partial void OntextChanging(string value);
    partial void OntextChanged();
    partial void Onyear_idChanging(System.Nullable<int> value);
    partial void Onyear_idChanged();
    partial void Onyear_weekChanging(System.Nullable<int> value);
    partial void Onyear_weekChanged();
    partial void Onsort_idChanging(System.Nullable<int> value);
    partial void Onsort_idChanged();
    partial void OnweekTypeIdChanging(System.Nullable<int> value);
    partial void OnweekTypeIdChanged();
    partial void Ondisplay_flagChanging(bool value);
    partial void Ondisplay_flagChanged();
    partial void OnpicksClosedChanging(bool value);
    partial void OnpicksClosedChanged();
    #endregion
		
		public NFL_week()
		{
			this._NFL_forums = new EntitySet<NFL_forum>(new Action<NFL_forum>(this.attach_NFL_forums), new Action<NFL_forum>(this.detach_NFL_forums));
			this._NFL_Matchups = new EntitySet<NFL_Matchup>(new Action<NFL_Matchup>(this.attach_NFL_Matchups), new Action<NFL_Matchup>(this.detach_NFL_Matchups));
			this._NFL_year = default(EntityRef<NFL_year>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_week", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int week
		{
			get
			{
				return this._week;
			}
			set
			{
				if ((this._week != value))
				{
					this.OnweekChanging(value);
					this.SendPropertyChanging();
					this._week = value;
					this.SendPropertyChanged("week");
					this.OnweekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exp_dt", DbType="DateTime NOT NULL")]
		public System.DateTime exp_dt
		{
			get
			{
				return this._exp_dt;
			}
			set
			{
				if ((this._exp_dt != value))
				{
					this.Onexp_dtChanging(value);
					this.SendPropertyChanging();
					this._exp_dt = value;
					this.SendPropertyChanged("exp_dt");
					this.Onexp_dtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_games", DbType="Int")]
		public System.Nullable<int> games
		{
			get
			{
				return this._games;
			}
			set
			{
				if ((this._games != value))
				{
					this.OngamesChanging(value);
					this.SendPropertyChanging();
					this._games = value;
					this.SendPropertyChanged("games");
					this.OngamesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_text", DbType="VarChar(50)")]
		public string text
		{
			get
			{
				return this._text;
			}
			set
			{
				if ((this._text != value))
				{
					this.OntextChanging(value);
					this.SendPropertyChanging();
					this._text = value;
					this.SendPropertyChanged("text");
					this.OntextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_year_id", DbType="Int")]
		public System.Nullable<int> year_id
		{
			get
			{
				return this._year_id;
			}
			set
			{
				if ((this._year_id != value))
				{
					if (this._NFL_year.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onyear_idChanging(value);
					this.SendPropertyChanging();
					this._year_id = value;
					this.SendPropertyChanged("year_id");
					this.Onyear_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_year_week", DbType="Int")]
		public System.Nullable<int> year_week
		{
			get
			{
				return this._year_week;
			}
			set
			{
				if ((this._year_week != value))
				{
					this.Onyear_weekChanging(value);
					this.SendPropertyChanging();
					this._year_week = value;
					this.SendPropertyChanged("year_week");
					this.Onyear_weekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sort_id", DbType="Int")]
		public System.Nullable<int> sort_id
		{
			get
			{
				return this._sort_id;
			}
			set
			{
				if ((this._sort_id != value))
				{
					this.Onsort_idChanging(value);
					this.SendPropertyChanging();
					this._sort_id = value;
					this.SendPropertyChanged("sort_id");
					this.Onsort_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weekTypeId", DbType="Int")]
		public System.Nullable<int> weekTypeId
		{
			get
			{
				return this._weekTypeId;
			}
			set
			{
				if ((this._weekTypeId != value))
				{
					this.OnweekTypeIdChanging(value);
					this.SendPropertyChanging();
					this._weekTypeId = value;
					this.SendPropertyChanged("weekTypeId");
					this.OnweekTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_display_flag", DbType="Bit NOT NULL")]
		public bool display_flag
		{
			get
			{
				return this._display_flag;
			}
			set
			{
				if ((this._display_flag != value))
				{
					this.Ondisplay_flagChanging(value);
					this.SendPropertyChanging();
					this._display_flag = value;
					this.SendPropertyChanged("display_flag");
					this.Ondisplay_flagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_picksClosed", DbType="Bit NOT NULL")]
		public bool picksClosed
		{
			get
			{
				return this._picksClosed;
			}
			set
			{
				if ((this._picksClosed != value))
				{
					this.OnpicksClosedChanging(value);
					this.SendPropertyChanging();
					this._picksClosed = value;
					this.SendPropertyChanged("picksClosed");
					this.OnpicksClosedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NFL_week_NFL_forum", Storage="_NFL_forums", ThisKey="week", OtherKey="week")]
		public EntitySet<NFL_forum> NFL_forums
		{
			get
			{
				return this._NFL_forums;
			}
			set
			{
				this._NFL_forums.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NFL_week_NFL_Matchup", Storage="_NFL_Matchups", ThisKey="week", OtherKey="week")]
		public EntitySet<NFL_Matchup> NFL_Matchups
		{
			get
			{
				return this._NFL_Matchups;
			}
			set
			{
				this._NFL_Matchups.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NFL_year_NFL_week", Storage="_NFL_year", ThisKey="year_id", OtherKey="id", IsForeignKey=true)]
		public NFL_year NFL_year
		{
			get
			{
				return this._NFL_year.Entity;
			}
			set
			{
				NFL_year previousValue = this._NFL_year.Entity;
				if (((previousValue != value) 
							|| (this._NFL_year.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NFL_year.Entity = null;
						previousValue.NFL_weeks.Remove(this);
					}
					this._NFL_year.Entity = value;
					if ((value != null))
					{
						value.NFL_weeks.Add(this);
						this._year_id = value.id;
					}
					else
					{
						this._year_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("NFL_year");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NFL_forums(NFL_forum entity)
		{
			this.SendPropertyChanging();
			entity.NFL_week = this;
		}
		
		private void detach_NFL_forums(NFL_forum entity)
		{
			this.SendPropertyChanging();
			entity.NFL_week = null;
		}
		
		private void attach_NFL_Matchups(NFL_Matchup entity)
		{
			this.SendPropertyChanging();
			entity.NFL_week = this;
		}
		
		private void detach_NFL_Matchups(NFL_Matchup entity)
		{
			this.SendPropertyChanging();
			entity.NFL_week = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NFL_userPicks")]
	public partial class NFL_userPick : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _username;
		
		private int _week;
		
		private string _picks;
		
		private System.DateTime _pick_dt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnweekChanging(int value);
    partial void OnweekChanged();
    partial void OnpicksChanging(string value);
    partial void OnpicksChanged();
    partial void Onpick_dtChanging(System.DateTime value);
    partial void Onpick_dtChanged();
    #endregion
		
		public NFL_userPick()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_week", DbType="Int NOT NULL")]
		public int week
		{
			get
			{
				return this._week;
			}
			set
			{
				if ((this._week != value))
				{
					this.OnweekChanging(value);
					this.SendPropertyChanging();
					this._week = value;
					this.SendPropertyChanged("week");
					this.OnweekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_picks", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string picks
		{
			get
			{
				return this._picks;
			}
			set
			{
				if ((this._picks != value))
				{
					this.OnpicksChanging(value);
					this.SendPropertyChanging();
					this._picks = value;
					this.SendPropertyChanged("picks");
					this.OnpicksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pick_dt", DbType="DateTime NOT NULL")]
		public System.DateTime pick_dt
		{
			get
			{
				return this._pick_dt;
			}
			set
			{
				if ((this._pick_dt != value))
				{
					this.Onpick_dtChanging(value);
					this.SendPropertyChanging();
					this._pick_dt = value;
					this.SendPropertyChanged("pick_dt");
					this.Onpick_dtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[log]")]
	public partial class log : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _type;
		
		private string _description;
		
		private System.DateTime _LogDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnLogDateChanging(System.DateTime value);
    partial void OnLogDateChanged();
    #endregion
		
		public log()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogDate", DbType="DateTime NOT NULL")]
		public System.DateTime LogDate
		{
			get
			{
				return this._LogDate;
			}
			set
			{
				if ((this._LogDate != value))
				{
					this.OnLogDateChanging(value);
					this.SendPropertyChanging();
					this._LogDate = value;
					this.SendPropertyChanged("LogDate");
					this.OnLogDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EmailLog")]
	public partial class EmailLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _EmailTo;
		
		private string _EmailSubject;
		
		private string _EmailBody;
		
		private string _EmailDisplayFrom;
		
		private System.DateTime _SendDate;
		
		private bool _Success;
		
		private string _Message;
		
		private string _Source;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnEmailToChanging(string value);
    partial void OnEmailToChanged();
    partial void OnEmailSubjectChanging(string value);
    partial void OnEmailSubjectChanged();
    partial void OnEmailBodyChanging(string value);
    partial void OnEmailBodyChanged();
    partial void OnEmailDisplayFromChanging(string value);
    partial void OnEmailDisplayFromChanged();
    partial void OnSendDateChanging(System.DateTime value);
    partial void OnSendDateChanged();
    partial void OnSuccessChanging(bool value);
    partial void OnSuccessChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    partial void OnSourceChanging(string value);
    partial void OnSourceChanged();
    #endregion
		
		public EmailLog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailTo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string EmailTo
		{
			get
			{
				return this._EmailTo;
			}
			set
			{
				if ((this._EmailTo != value))
				{
					this.OnEmailToChanging(value);
					this.SendPropertyChanging();
					this._EmailTo = value;
					this.SendPropertyChanged("EmailTo");
					this.OnEmailToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailSubject", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string EmailSubject
		{
			get
			{
				return this._EmailSubject;
			}
			set
			{
				if ((this._EmailSubject != value))
				{
					this.OnEmailSubjectChanging(value);
					this.SendPropertyChanging();
					this._EmailSubject = value;
					this.SendPropertyChanged("EmailSubject");
					this.OnEmailSubjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailBody", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string EmailBody
		{
			get
			{
				return this._EmailBody;
			}
			set
			{
				if ((this._EmailBody != value))
				{
					this.OnEmailBodyChanging(value);
					this.SendPropertyChanging();
					this._EmailBody = value;
					this.SendPropertyChanged("EmailBody");
					this.OnEmailBodyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailDisplayFrom", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string EmailDisplayFrom
		{
			get
			{
				return this._EmailDisplayFrom;
			}
			set
			{
				if ((this._EmailDisplayFrom != value))
				{
					this.OnEmailDisplayFromChanging(value);
					this.SendPropertyChanging();
					this._EmailDisplayFrom = value;
					this.SendPropertyChanged("EmailDisplayFrom");
					this.OnEmailDisplayFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendDate", DbType="DateTime NOT NULL")]
		public System.DateTime SendDate
		{
			get
			{
				return this._SendDate;
			}
			set
			{
				if ((this._SendDate != value))
				{
					this.OnSendDateChanging(value);
					this.SendPropertyChanging();
					this._SendDate = value;
					this.SendPropertyChanged("SendDate");
					this.OnSendDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Success", DbType="Bit NOT NULL")]
		public bool Success
		{
			get
			{
				return this._Success;
			}
			set
			{
				if ((this._Success != value))
				{
					this.OnSuccessChanging(value);
					this.SendPropertyChanging();
					this._Success = value;
					this.SendPropertyChanged("Success");
					this.OnSuccessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this.OnMessageChanging(value);
					this.SendPropertyChanging();
					this._Message = value;
					this.SendPropertyChanged("Message");
					this.OnMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Source", DbType="VarChar(MAX)")]
		public string Source
		{
			get
			{
				return this._Source;
			}
			set
			{
				if ((this._Source != value))
				{
					this.OnSourceChanging(value);
					this.SendPropertyChanging();
					this._Source = value;
					this.SendPropertyChanged("Source");
					this.OnSourceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NFL_forum")]
	public partial class NFL_forum : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _week;
		
		private string _username;
		
		private System.Nullable<int> _ref_id;
		
		private string _comment;
		
		private string _title;
		
		private System.Nullable<System.DateTime> _insert_dt;
		
		private System.Nullable<bool> _alerted;
		
		private bool _emailOnReply;
		
		private EntityRef<NFL_week> _NFL_week;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnweekChanging(System.Nullable<int> value);
    partial void OnweekChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void Onref_idChanging(System.Nullable<int> value);
    partial void Onref_idChanged();
    partial void OncommentChanging(string value);
    partial void OncommentChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void Oninsert_dtChanging(System.Nullable<System.DateTime> value);
    partial void Oninsert_dtChanged();
    partial void OnalertedChanging(System.Nullable<bool> value);
    partial void OnalertedChanged();
    partial void OnemailOnReplyChanging(bool value);
    partial void OnemailOnReplyChanged();
    #endregion
		
		public NFL_forum()
		{
			this._NFL_week = default(EntityRef<NFL_week>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_week", DbType="Int")]
		public System.Nullable<int> week
		{
			get
			{
				return this._week;
			}
			set
			{
				if ((this._week != value))
				{
					if (this._NFL_week.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnweekChanging(value);
					this.SendPropertyChanging();
					this._week = value;
					this.SendPropertyChanged("week");
					this.OnweekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ref_id", DbType="Int")]
		public System.Nullable<int> ref_id
		{
			get
			{
				return this._ref_id;
			}
			set
			{
				if ((this._ref_id != value))
				{
					this.Onref_idChanging(value);
					this.SendPropertyChanging();
					this._ref_id = value;
					this.SendPropertyChanged("ref_id");
					this.Onref_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comment", DbType="VarChar(MAX)")]
		public string comment
		{
			get
			{
				return this._comment;
			}
			set
			{
				if ((this._comment != value))
				{
					this.OncommentChanging(value);
					this.SendPropertyChanging();
					this._comment = value;
					this.SendPropertyChanged("comment");
					this.OncommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="VarChar(20)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insert_dt", DbType="DateTime")]
		public System.Nullable<System.DateTime> insert_dt
		{
			get
			{
				return this._insert_dt;
			}
			set
			{
				if ((this._insert_dt != value))
				{
					this.Oninsert_dtChanging(value);
					this.SendPropertyChanging();
					this._insert_dt = value;
					this.SendPropertyChanged("insert_dt");
					this.Oninsert_dtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alerted", DbType="Bit")]
		public System.Nullable<bool> alerted
		{
			get
			{
				return this._alerted;
			}
			set
			{
				if ((this._alerted != value))
				{
					this.OnalertedChanging(value);
					this.SendPropertyChanging();
					this._alerted = value;
					this.SendPropertyChanged("alerted");
					this.OnalertedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailOnReply")]
		public bool emailOnReply
		{
			get
			{
				return this._emailOnReply;
			}
			set
			{
				if ((this._emailOnReply != value))
				{
					this.OnemailOnReplyChanging(value);
					this.SendPropertyChanging();
					this._emailOnReply = value;
					this.SendPropertyChanged("emailOnReply");
					this.OnemailOnReplyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NFL_week_NFL_forum", Storage="_NFL_week", ThisKey="week", OtherKey="week", IsForeignKey=true)]
		public NFL_week NFL_week
		{
			get
			{
				return this._NFL_week.Entity;
			}
			set
			{
				NFL_week previousValue = this._NFL_week.Entity;
				if (((previousValue != value) 
							|| (this._NFL_week.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NFL_week.Entity = null;
						previousValue.NFL_forums.Remove(this);
					}
					this._NFL_week.Entity = value;
					if ((value != null))
					{
						value.NFL_forums.Add(this);
						this._week = value.week;
					}
					else
					{
						this._week = default(Nullable<int>);
					}
					this.SendPropertyChanged("NFL_week");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.emailSubscriptionTypes")]
	public partial class emailSubscriptionType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private bool _autoEnroll;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnautoEnrollChanging(bool value);
    partial void OnautoEnrollChanged();
    #endregion
		
		public emailSubscriptionType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_autoEnroll", DbType="Bit NOT NULL")]
		public bool autoEnroll
		{
			get
			{
				return this._autoEnroll;
			}
			set
			{
				if ((this._autoEnroll != value))
				{
					this.OnautoEnrollChanging(value);
					this.SendPropertyChanging();
					this._autoEnroll = value;
					this.SendPropertyChanged("autoEnroll");
					this.OnautoEnrollChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.users")]
	public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _name;
		
		private string _encPW;
		
		private string _ip_address;
		
		private System.Nullable<System.DateTime> _registration_dt;
		
		private string _email;
		
		private System.Nullable<System.DateTime> _stay_logged_on_dt;
		
		private System.Nullable<System.DateTime> _birthday;
		
		private bool _IsActive;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnencPWChanging(string value);
    partial void OnencPWChanged();
    partial void Onip_addressChanging(string value);
    partial void Onip_addressChanged();
    partial void Onregistration_dtChanging(System.Nullable<System.DateTime> value);
    partial void Onregistration_dtChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onstay_logged_on_dtChanging(System.Nullable<System.DateTime> value);
    partial void Onstay_logged_on_dtChanged();
    partial void OnbirthdayChanging(System.Nullable<System.DateTime> value);
    partial void OnbirthdayChanged();
    partial void OnIsActiveChanging(bool value);
    partial void OnIsActiveChanged();
    #endregion
		
		public user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_encPW", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string encPW
		{
			get
			{
				return this._encPW;
			}
			set
			{
				if ((this._encPW != value))
				{
					this.OnencPWChanging(value);
					this.SendPropertyChanging();
					this._encPW = value;
					this.SendPropertyChanged("encPW");
					this.OnencPWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ip_address", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ip_address
		{
			get
			{
				return this._ip_address;
			}
			set
			{
				if ((this._ip_address != value))
				{
					this.Onip_addressChanging(value);
					this.SendPropertyChanging();
					this._ip_address = value;
					this.SendPropertyChanged("ip_address");
					this.Onip_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_registration_dt", DbType="DateTime")]
		public System.Nullable<System.DateTime> registration_dt
		{
			get
			{
				return this._registration_dt;
			}
			set
			{
				if ((this._registration_dt != value))
				{
					this.Onregistration_dtChanging(value);
					this.SendPropertyChanging();
					this._registration_dt = value;
					this.SendPropertyChanged("registration_dt");
					this.Onregistration_dtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stay_logged_on_dt", DbType="DateTime")]
		public System.Nullable<System.DateTime> stay_logged_on_dt
		{
			get
			{
				return this._stay_logged_on_dt;
			}
			set
			{
				if ((this._stay_logged_on_dt != value))
				{
					this.Onstay_logged_on_dtChanging(value);
					this.SendPropertyChanging();
					this._stay_logged_on_dt = value;
					this.SendPropertyChanged("stay_logged_on_dt");
					this.Onstay_logged_on_dtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthday", DbType="DateTime")]
		public System.Nullable<System.DateTime> birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if ((this._birthday != value))
				{
					this.OnbirthdayChanging(value);
					this.SendPropertyChanging();
					this._birthday = value;
					this.SendPropertyChanged("birthday");
					this.OnbirthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NFL_years")]
	public partial class NFL_year : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _text;
		
		private int _year;
		
		private int _sport_id;
		
		private EntitySet<NFL_week> _NFL_weeks;
		
		private EntityRef<NFL_sport> _NFL_sport;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntextChanging(string value);
    partial void OntextChanged();
    partial void OnyearChanging(int value);
    partial void OnyearChanged();
    partial void Onsport_idChanging(int value);
    partial void Onsport_idChanged();
    #endregion
		
		public NFL_year()
		{
			this._NFL_weeks = new EntitySet<NFL_week>(new Action<NFL_week>(this.attach_NFL_weeks), new Action<NFL_week>(this.detach_NFL_weeks));
			this._NFL_sport = default(EntityRef<NFL_sport>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_text", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string text
		{
			get
			{
				return this._text;
			}
			set
			{
				if ((this._text != value))
				{
					this.OntextChanging(value);
					this.SendPropertyChanging();
					this._text = value;
					this.SendPropertyChanged("text");
					this.OntextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_year", DbType="Int NOT NULL")]
		public int year
		{
			get
			{
				return this._year;
			}
			set
			{
				if ((this._year != value))
				{
					this.OnyearChanging(value);
					this.SendPropertyChanging();
					this._year = value;
					this.SendPropertyChanged("year");
					this.OnyearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sport_id", DbType="Int NOT NULL")]
		public int sport_id
		{
			get
			{
				return this._sport_id;
			}
			set
			{
				if ((this._sport_id != value))
				{
					if (this._NFL_sport.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsport_idChanging(value);
					this.SendPropertyChanging();
					this._sport_id = value;
					this.SendPropertyChanged("sport_id");
					this.Onsport_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NFL_year_NFL_week", Storage="_NFL_weeks", ThisKey="id", OtherKey="year_id")]
		public EntitySet<NFL_week> NFL_weeks
		{
			get
			{
				return this._NFL_weeks;
			}
			set
			{
				this._NFL_weeks.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NFL_sport_NFL_year", Storage="_NFL_sport", ThisKey="sport_id", OtherKey="id", IsForeignKey=true)]
		public NFL_sport NFL_sport
		{
			get
			{
				return this._NFL_sport.Entity;
			}
			set
			{
				NFL_sport previousValue = this._NFL_sport.Entity;
				if (((previousValue != value) 
							|| (this._NFL_sport.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NFL_sport.Entity = null;
						previousValue.NFL_years.Remove(this);
					}
					this._NFL_sport.Entity = value;
					if ((value != null))
					{
						value.NFL_years.Add(this);
						this._sport_id = value.id;
					}
					else
					{
						this._sport_id = default(int);
					}
					this.SendPropertyChanged("NFL_sport");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NFL_weeks(NFL_week entity)
		{
			this.SendPropertyChanging();
			entity.NFL_year = this;
		}
		
		private void detach_NFL_weeks(NFL_week entity)
		{
			this.SendPropertyChanging();
			entity.NFL_year = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NFL_sports")]
	public partial class NFL_sport : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private EntitySet<NFL_year> _NFL_years;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public NFL_sport()
		{
			this._NFL_years = new EntitySet<NFL_year>(new Action<NFL_year>(this.attach_NFL_years), new Action<NFL_year>(this.detach_NFL_years));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NFL_sport_NFL_year", Storage="_NFL_years", ThisKey="id", OtherKey="sport_id")]
		public EntitySet<NFL_year> NFL_years
		{
			get
			{
				return this._NFL_years;
			}
			set
			{
				this._NFL_years.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NFL_years(NFL_year entity)
		{
			this.SendPropertyChanging();
			entity.NFL_sport = this;
		}
		
		private void detach_NFL_years(NFL_year entity)
		{
			this.SendPropertyChanging();
			entity.NFL_sport = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NFL_Matchups")]
	public partial class NFL_Matchup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _week;
		
		private string _away;
		
		private string _home;
		
		private string _winner;
		
		private System.Nullable<int> _home_score;
		
		private System.Nullable<int> _away_score;
		
		private string _status;
		
		private string _scheduled;
		
		private System.Nullable<long> _eid;
		
		private System.Nullable<int> _year_week;
		
		private EntityRef<NFL_week> _NFL_week;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnweekChanging(int value);
    partial void OnweekChanged();
    partial void OnawayChanging(string value);
    partial void OnawayChanged();
    partial void OnhomeChanging(string value);
    partial void OnhomeChanged();
    partial void OnwinnerChanging(string value);
    partial void OnwinnerChanged();
    partial void Onhome_scoreChanging(System.Nullable<int> value);
    partial void Onhome_scoreChanged();
    partial void Onaway_scoreChanging(System.Nullable<int> value);
    partial void Onaway_scoreChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OnscheduledChanging(string value);
    partial void OnscheduledChanged();
    partial void OneidChanging(System.Nullable<long> value);
    partial void OneidChanged();
    partial void Onyear_weekChanging(System.Nullable<int> value);
    partial void Onyear_weekChanged();
    #endregion
		
		public NFL_Matchup()
		{
			this._NFL_week = default(EntityRef<NFL_week>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_week", DbType="Int NOT NULL")]
		public int week
		{
			get
			{
				return this._week;
			}
			set
			{
				if ((this._week != value))
				{
					if (this._NFL_week.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnweekChanging(value);
					this.SendPropertyChanging();
					this._week = value;
					this.SendPropertyChanged("week");
					this.OnweekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_away", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string away
		{
			get
			{
				return this._away;
			}
			set
			{
				if ((this._away != value))
				{
					this.OnawayChanging(value);
					this.SendPropertyChanging();
					this._away = value;
					this.SendPropertyChanged("away");
					this.OnawayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_home", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string home
		{
			get
			{
				return this._home;
			}
			set
			{
				if ((this._home != value))
				{
					this.OnhomeChanging(value);
					this.SendPropertyChanging();
					this._home = value;
					this.SendPropertyChanged("home");
					this.OnhomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_winner", DbType="VarChar(50)")]
		public string winner
		{
			get
			{
				return this._winner;
			}
			set
			{
				if ((this._winner != value))
				{
					this.OnwinnerChanging(value);
					this.SendPropertyChanging();
					this._winner = value;
					this.SendPropertyChanged("winner");
					this.OnwinnerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_home_score", DbType="Int")]
		public System.Nullable<int> home_score
		{
			get
			{
				return this._home_score;
			}
			set
			{
				if ((this._home_score != value))
				{
					this.Onhome_scoreChanging(value);
					this.SendPropertyChanging();
					this._home_score = value;
					this.SendPropertyChanged("home_score");
					this.Onhome_scoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_away_score", DbType="Int")]
		public System.Nullable<int> away_score
		{
			get
			{
				return this._away_score;
			}
			set
			{
				if ((this._away_score != value))
				{
					this.Onaway_scoreChanging(value);
					this.SendPropertyChanging();
					this._away_score = value;
					this.SendPropertyChanged("away_score");
					this.Onaway_scoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(5)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scheduled", DbType="VarChar(20)")]
		public string scheduled
		{
			get
			{
				return this._scheduled;
			}
			set
			{
				if ((this._scheduled != value))
				{
					this.OnscheduledChanging(value);
					this.SendPropertyChanging();
					this._scheduled = value;
					this.SendPropertyChanged("scheduled");
					this.OnscheduledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eid", DbType="BigInt")]
		public System.Nullable<long> eid
		{
			get
			{
				return this._eid;
			}
			set
			{
				if ((this._eid != value))
				{
					this.OneidChanging(value);
					this.SendPropertyChanging();
					this._eid = value;
					this.SendPropertyChanged("eid");
					this.OneidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_year_week", DbType="Int")]
		public System.Nullable<int> year_week
		{
			get
			{
				return this._year_week;
			}
			set
			{
				if ((this._year_week != value))
				{
					this.Onyear_weekChanging(value);
					this.SendPropertyChanging();
					this._year_week = value;
					this.SendPropertyChanged("year_week");
					this.Onyear_weekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NFL_week_NFL_Matchup", Storage="_NFL_week", ThisKey="week", OtherKey="week", IsForeignKey=true)]
		public NFL_week NFL_week
		{
			get
			{
				return this._NFL_week.Entity;
			}
			set
			{
				NFL_week previousValue = this._NFL_week.Entity;
				if (((previousValue != value) 
							|| (this._NFL_week.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NFL_week.Entity = null;
						previousValue.NFL_Matchups.Remove(this);
					}
					this._NFL_week.Entity = value;
					if ((value != null))
					{
						value.NFL_Matchups.Add(this);
						this._week = value.week;
					}
					else
					{
						this._week = default(int);
					}
					this.SendPropertyChanged("NFL_week");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
